### ISSUE TITLE
Git игнорирует исключения gitignore

### ISSUE THREAD

**Issue by Murrk** [Murrk/CashbackHackServiceCI#1]
Ожидание: файл указанный в файле .gitignore как !gradle/wrapper/gradle-wrapper.jar не будет добавлен в игнорируемые
Реальность: файл проигнорирован

Шаги:
1. Создала проект в Idea
2. Добавила в папку проекта файл gitignore из демо репозитория
3. Инициировала в Idea git репозиторий
4. Сделала git add
5. Сделала первый коммит
6. Привязала удаленный репозиторий
7. Запушила
8. Добавила appveyor
9. Получила ошибку, что не хватает данного файла

Решение: добавила его принудительно с флагом -f.
Есть другие варианты быстро привести файлы в соответствие c gitignore?

**Comment by coursar** [comment]
Поменять .gitignore, всё, что с ! добавить в конец файла.
